apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  volumes:
  - name: log-data
    emptyDir: {}
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: kaerhae/devops-with-kube-todo-app:v0.0.3
          env:
          - name: PORT
            value: "9000"