apiVersion: v1
kind: Service
metadata:
  namespace: dwk-applications
  name: log-output-svc
spec:
  type: ClusterIP
  selector:
    app: log-output
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 8888