apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dwk-project
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
      - name: todo-data
        persistentVolumeClaim:
          claimName: devops-with-kube-project-pvc
      containers:
        - name: todo-app
          image: kaerhae/devops-with-kube-todo-app:v0.0.6
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "9000"
          - name: IMAGE_FILE_PATH
            value: /usr/src/data
          - name: TODO_BACKEND_BASEURL
            value: todo-backend-svc:2344
          volumeMounts:
          - name: todo-data
            mountPath: /usr/src/data