apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-with-kube-pv
spec:
  storageClassName: devops-with-kube-pv
  capacity:
    storage: 1Gi 
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  local:
    path: /data/kube # Created with docker exec k3d-k3s-default-agent-0 mkdir -p /data/kube
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0