apiVersion: v1
kind: Service
metadata:
  namespace: dwk-project
  name: todo-backend-svc
spec:
  type: ClusterIP
  selector:
    app: todo-backend
  ports:
    - port: 2344
      protocol: TCP
      targetPort: 9090