apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dwk-project
  name: devops-with-kube-project-pvc
spec:
  storageClassName: devops-with-kube-project-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi