# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.directories.outputs.directories }}
    steps:
      - name: Define Directories
        id: directories
        run: |
          echo 'directories=["Part1", "Part2"]' >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      matrix:
        part: ${{ fromJSON(needs.define-matrix.outputs.directories) }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build Logger Writer
      working-directory: ${{ matrix.part }}/logger-app
      run: go build cmd/writer/main.go

    - name: Build Logger Reader
      working-directory: ${{ matrix.part }}/logger-app
      run: go build cmd/reader/main.go

    - name: Test
      working-directory: ${{ matrix.part }}/logger-app
      run: go test ./...
